### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by macromillion** [leinelissen/jellyfin-audio-player#100]
- Make the artist name clickable and send you to the artist page upon click
- Add a visualizer that shows when you tap the album art, replacing the album art (idea from PlexAmp)
- Add lyrics support
    - Add search by lyrics
    - Show lyrics in replacement of album art (to save space)
- Give the option to change the icon to a dark theme
- Lower the darkness of the orange color, I feel like its too dark and makes the text hard to read at times especially in dark mode
- Round out the corners of the letters bar that shows at the top in the "All Albums" menu
- Play random or related songs at the end of a selected song unless set otherwise (infinite playback button)

**Comment by PauFCB** [comment]
Good points! Also a artist bio and poster when you go the the artist section wold be nice.

**Comment by leinelissen** [comment]
Hey @macromillion, @PauFCB. I really like these suggestions. Let me see if I can work with them. To be frank with you, I don't have a lot of free time to work on this currently, so if you guys want to give it a go I would be happy to give you some pointers. Cheers!
