### ISSUE TITLE
Unable to press "Play [album|playlist]", "Shuffle [album|playlist]" or the first song in the list

### ISSUE THREAD

**Issue by haleksandre** [leinelissen/jellyfin-audio-player#101]
I'm getting a weird bug where I can't press the "Play [album|playlist]", "Shuffle [album|playlist]" or the first song in the list. but I seem to be able to press & play any other song in the list.

The current workaround I'm using to play the list from the beginning is by pressing the 2nd song & pressing track back to the 1st song.

I'm using the app on a Samsung S21 Ultra running One UI 4.1 on Android 12.

**Comment by leinelissen** [comment]
Hey there, thanks for the feedback! I'm investigating it in issue #99, so I'll be closing this one as duplicate for now.
