### ISSUE TITLE
[Bug] The download feature does not work anymore in 1.2.7

### ISSUE THREAD

**Issue by kuflierl** [leinelissen/jellyfin-audio-player#102]
I did a fresh install of jellyfin 1.2.7 (Iphone 6s IOS 15.7 Testflight). Streaming mode works, but attempting to download any known good tracks (batch or single) fails. The progress ring does show up next to the track in the album, but doesn't download anything (my server also didn't register any noticeable data throughput). The download also doesn't show up in the downloads category. I removed and retried the app a few times with a 100% reproducibility.

**Comment by iamironz** [comment]
The same for me. Downloading just does not work, loading icons appears but caching itself is never happens

**Comment by kuflierl** [comment]
> The same for me. Downloading just does not work, loading icons appears but caching itself is never happens

Icon caching is another problem. If your audio has the icon embedded, it will still work. But if it's just saved by jellyfin it will not.

**Comment by kuflierl** [comment]
I am now going to close this issue as it was solved
