### ISSUE TITLE
White screen when connect to self-signed certifcated jellyfin

### ISSUE THREAD

**Issue by zuoez02** [leinelissen/jellyfin-audio-player#110]
I built my Jellyfin server with my self-signed certificate, and port is not 443. It became a white screen after setting Jellyfin server.

**Comment by leinelissen** [comment]
Hey @zuoez02. Unfortunately self-signed certificates are not supported as this an OS-level config that we cannot change. Same goes for HTTP connections, as we cannot release the app on the App Store if we were to enable App Transport Security. Your best bet is either a) getting a free HTTPS certificate using e.g. LetsEncrypt; or b) adding the certificate as a trusted certificate in your OS (e.g. [iOS](https://apple.stackexchange.com/questions/283348/how-do-i-trust-a-self-signed-certificate-in-ios-10-3)). Please do share how you managed to resolve the issue for other people coming in.

**Comment by zuoez02** [comment]
I use the app on Android, and I have imported the self-signed certificate in the system configuration. Some of app can use it for https connections, such as Bitwarden, Tachiyomi, Home Assistant。

Or can we add an checkbox to ignore the warning of self-signed certificate?

发件人: Lei Nelissen ***@***.***>
发送时间: 2022年11月29日 17:30
收件人: leinelissen/jellyfin-audio-player ***@***.***>
抄送: Luto Yvan ***@***.***>; Mention ***@***.***>
主题: Re: [leinelissen/jellyfin-audio-player] White screen when connect to self-signed certifcated jellyfin (Issue #110)


Hey @zuoez02<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzuoez02&data=05%7C01%7C%7C252840543070428c21d408dad1ec59cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638053110303412014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QqtetLIjpPBm69pFz3JaHckWyAI%2BqvqKtqAFmWFgsGk%3D&reserved=0>. Unfortunately self-signed certificates are not supported as this an OS-level config that we cannot change. Same goes for HTTP connections, as we cannot release the app on the App Store if we were to enable App Transport Security. Your best bet is either a) getting a free HTTPS certificate using e.g. LetsEncrypt; or b) adding the certificate as a trusted certificate in your OS (e.g. iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapple.stackexchange.com%2Fquestions%2F283348%2Fhow-do-i-trust-a-self-signed-certificate-in-ios-10-3&data=05%7C01%7C%7C252840543070428c21d408dad1ec59cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638053110303412014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cyeiWiW3KWghaKjSKrIFkiBWNXER2wni1zErM0E0ovg%3D&reserved=0>). Please do share how you managed to resolve the issue for other people coming in.

―

**Comment by leinelissen** [comment]
Okay let me see if I can get a quick sense of what error is thrown on Android.

**Comment by KNIX3** [comment]
I have the same problem. My root certificate authority is added to Android at the OS level so it should work, and does in other apps, but doesn't in Fintunes.
