### ISSUE TITLE
[visual issue] set server has bad contrast in dark mode

### ISSUE THREAD

**Issue by kuflierl** [leinelissen/jellyfin-audio-player#111]
Set server uses black text on black background code in dark mode

Fintunes 2.0.1 on iOS 15.7.1

**Comment by kuflierl** [comment]
![image](https://user-images.githubusercontent.com/41301536/205609221-cc3d50ab-0a25-49ef-90cc-eb8c2b360f5e.jpeg)

**Comment by leinelissen** [comment]
Hey @kuflierl, this is true for all inputs and it's a regression bug from fixing the input box. I'll try and have a look soon.

**Comment by kuflierl** [comment]
looks great!

> This should be fixed in v2.0.2, which is on its way to TestFlight and the App Store. Would love to hear you confirm the issue as resolved. Cheers!

looks great!
