### ISSUE TITLE
Album art is not displaying for all but first album

### ISSUE THREAD

**Issue by leinelissen** [leinelissen/jellyfin-audio-player#13]
A bug report came in from TestFlight mentioning that album art is not displaying on any album, except for the first one in queue? At least, investigate whether album art is correctly being displayed with the current version.

**Comment by nellistc** [comment]
This may have been from me. I can see artwork in the Music tab, but not in Now Playing.

Happy to do more testing or provide more info as required.

**Comment by leinelissen** [comment]
I think I have received multiple reports for this one 😅. I'll try to investigate what's happening there.
