### ISSUE TITLE
[bug] All Albums button

### ISSUE THREAD

**Issue by FaboThePlayer** [leinelissen/jellyfin-audio-player#130]
When I press All Albums at the top, the app always completely crashes.

**Comment by leinelissen** [comment]
Hey @FaboThePlayer, thanks for reporting the issue. Can you give me some details on your OS, Jellyfin server version and details such as if it is running HTTPS? Also, does the recent album view work and can you play back music from that screen? Lastly, do you have an estimate for much albums are in your Jellfin library? Cheers!

**Comment by leinelissen** [comment]
Hey there everyone, thanks for sticking around. I've managed to resolve this issue in v2.0.4, which has just been released. I would love to hear whether this fixes your issue.
