### ISSUE TITLE
[bug] fintunes immediately crashes when viewing playlists tab in ios

### ISSUE THREAD

**Issue by Behem07h** [leinelissen/jellyfin-audio-player#135]
after the latest testflight update 2.0.4 (61), fintunes immediately crashes when attempting to view the playlists tab

**Comment by leinelissen** [comment]
Hey, thanks for reporting this! I can reproduce it, let me get to a fix. I've expired v2.0.4, so you can move back to v2.0.3 to get a working version.

**Comment by leinelissen** [comment]
I managed to track down the issue and it is fixed in v2.0.5. The version is on its way to TestFlight and shortly thereafter the App Store as well. Thanks again for reporting this!
