### ISSUE TITLE
[bug] ios, after updating to 2.0.4 (61) and then downgrading to 2.0.3 (53), previously downloaded songs fail to load (infinite loading icon) 

### ISSUE THREAD

**Issue by Behem07h** [leinelissen/jellyfin-audio-player#136]
after updating to 2.0.4 (61) and then downgrading to 2.0.3 (53) via the testflight rollback earlier today, songs that had previously been downloaded for local playback fail to load (infinite loading icon) 

i have been able to circumvent this bug by deleting and redownloading all my media

**Comment by leinelissen** [comment]
Hey @Behem07h, thanks for reporting this. I've heard stories before of media files struggling to be transferred across app updates. I've never been able to reproduce the problem though, so it's hard for me to look at a particular fix. Can you at least check if it happens again when v2.0.5 hits TestFlight?

**Comment by Behem07h** [comment]
sure, i'll keep a look out. conveniently local playback is the only way for me to play my media due to that pesky streaming bug, so if it does happen again i should catch it pretty easily

**Comment by Behem07h** [comment]
Can confirm that 2.0.3 to 2.0.5 has incurred the same bug

**Comment by leinelissen** [comment]
Thanks for confirming it. That proves it's a consistent bug at least. The weird thing is that the settings do persist, so it's got something to do specifically with file storage. Let me see if I can find out the underlying problem.

**Comment by kuflierl** [comment]
I would also like to confirm this bug. I also have to redownload everything after the update

**Comment by Behem07h** [comment]
this is now fixed on my device as of the latest update, thanks

**Comment by PauFCB** [comment]
Seems that update fix and I can download every playlist now.
A suggestion: make a Play all downloads/Shuffle inside the download section. Thanks for your work!

**Comment by Behem07h** [comment]
after the new update i seem to be getting a new having an issue downloading mka files specfically, i've detailed that in https://github.com/leinelissen/jellyfin-audio-player/issues/162#issue-1803889693. not sure if this is related to the update or if it's something else that changed
