### ISSUE TITLE
[Feature request] add theme option in settings

### ISSUE THREAD

**Issue by kuflierl** [leinelissen/jellyfin-audio-player#138]
Would it be possible to add a option to manually set the theme in settings?

**Comment by leinelissen** [comment]
I assume you mean switching between dark and light mode manually? I personally favour following the OS settings, but is there a particular use case that you would prefer having?

**Comment by PauFCB** [comment]
I think this is a good suggestion too, bc personaly, I like the dark theme more but want to keep the default system settings on light mode.
