### ISSUE TITLE
Add support for playback reporting

### ISSUE THREAD

**Issue by the-r0cket06** [leinelissen/jellyfin-audio-player#14]
Would you be willing to investigate implementing playback reporting?

**Comment by leinelissen** [comment]
I'd consider it, but admittedly it would be pretty low on the priority list at this point. If you feel adventurous, I'd be happy to accept a pull request that implements the functionality. I can point you where to look for specific stuff if you need any help.

**Comment by attie** [comment]
Is this a duplicate of #62? (there's more activity / interest over there)

**Comment by leinelissen** [comment]
Yeah it would be good to track it in a single issue. Duplicate of #62
