### ISSUE TITLE
Cover referesh and playlist bug

### ISSUE THREAD

**Issue by PauFCB** [leinelissen/jellyfin-audio-player#142]
Hi Lei, just found two bugs:
1. When I am playing a song with the now playing screen open, I turn off the screen, then it changes to the next song (or I change it) and if I turn the screen back on, the cover of that new song is not updated, only the name, and I have to touch anywhere on the screen to update the cover.
2. Even If I trying to delete cache and reinstalling the app, only let me download one full playlist, when the download it’s complete, I can’t download any other playlist, when I click the download button don’t do anything or only download 2 random songs in the middle (i found that always the same two).

thanks!

**Comment by leinelissen** [comment]
Hey @PauFCB, thanks for the report as always. I'll take a look and see what I can do. As for the second issue, this may be due to some inefficiencies with large playlists. I assume the first playlist is pretty large in this case, right?

**Comment by PauFCB** [comment]
Yes, and now I can’t download anyone as the playlist grow over 100 songs
