### ISSUE TITLE
Timer to stop music

### ISSUE THREAD

**Issue by MrLaaky** [leinelissen/jellyfin-audio-player#154]
Awesome app! Is it possible to stop the music after x minutes of time?
Kind regards

**Comment by tehami02** [comment]
Yes It is possible. Are u owner of jellyfin? Do u want to introduce this feature ?

**Comment by leinelissen** [comment]
Hi @MrLaaky, thanks for the input! Implementing it would be possible, though admittedly not very straightforward. What particular use case do you have in mind?

**Comment by MrLaaky** [comment]
When you go to sleep you, I leave a playlist to play music to easier fall asleep.  If I don't want the music to play all night, I have to set a timer to stop the music after 60 minutes.
That's it. Thank you for the reply.

**Comment by leinelissen** [comment]
Hey there. I'm not sure whether you're on Android or iOS, but it's possible to build this using iOS Shortcuts. You can create a shortcut that consists of the Wait task and the Media Play/Pause task. If you run this simultaneously with Fintunes, it's bound to pause the music after the wait duration. From what I can gather online, similar options exist for Android as well. I would much prefer such a solution because doing things in the background is inefficient and a bit tricky to get right. Hope this help you on the way.

**Comment by tehami02** [comment]
Maybe we use "react-native-background-timer" (https://www.npmjs.com/package/react-native-background-timer) and some UI changes to implement this feature.

**Comment by leinelissen** [comment]
I am open to suggestions, but I would favour a solution outside of the app.

**Comment by MrLaaky** [comment]
Whatever @leinelissen says, goes.
What I had in mind was something like in Deezer, where you have an icon for the timer.
If the pull request is made and denied I will confirm the bounty as completed. @tehami02

**Comment by tehami02** [comment]
@leinelissen @MrLaaky If u want something outside of app, what do u suggest ? Do u think we can use AlarmManager (https://developer.android.com/reference/android/app/AlarmManager) to implement this feature ?

**Comment by ben-mathu** [comment]
I have created this feature, please review the PR Timer to Stop Music #168

**Comment by makeasnek** [comment]
Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues

**Comment by kuflierl** [comment]
> I am open to suggestions, but I would favour a solution outside of the app.

Many great music player apps have sleep timers including the vlc app (both ios and android). It's quite the popular feature among ppl who want to listen to music in bed. Having to open a separate app just to add timer functionality seems like an obvious pain-point to me. I also don't quite understand your argument that doing things in the background is inefficient. Could you elaborate on that? You already have to handle audio, album shuffling and looping behaviors in the background.

**Comment by leinelissen** [comment]
This is now available in v2.3.0 🚀
