### ISSUE TITLE
Mark app as Mac compatible on TestFlight

### ISSUE THREAD

**Issue by fuomag9** [leinelissen/jellyfin-audio-player#161]
I'd love to run the app on Mac arm, as it has native support for Mac apps. Currently this is not possible in the TestFlight version since it's marked as incompatible with Mac and I can't install it

![image](https://github.com/leinelissen/jellyfin-audio-player/assets/1580624/b32ec0ef-4adc-4251-8277-8a9747625256)

App Store version can be installed and works, but cannot be resized

![image](https://github.com/leinelissen/jellyfin-audio-player/assets/1580624/1924a6b1-d474-4e17-a6ff-b686340c3483)

**Comment by leinelissen** [comment]
This is now fixed.
