### ISSUE TITLE
Downloaded MKA files arent actually downloaded and total downloaded size stuck at 0 bytes

### ISSUE THREAD

**Issue by Behem07h** [leinelissen/jellyfin-audio-player#162]
In testing the new update i decided to delete all my old downloads and redownload them to see what would happen. 
Strangely, the download process would go through and the list of files would show in the downloaded files list, but the total downloaded size shows as 0, and the files dont seem to play from local playback. There is no "retry failed downloads" option. 

This only seems to occur on my MKA files (which i had been using just fine via local playback previously), downloading MP4 files works as expected.

**Comment by leinelissen** [comment]
Hey there! iOS and Android cannot play back MKA files, so they need to be transcoded on-the-fly. This works quite poorly currently, and I'm waiting for some flags to hit the next Jellyfin release so I can solve that problem. That work is being tracked in #97. This will also impact the ability to properly download transcoded files. Until then, I suggest using formats that are natively support by the OS you're using.
