### ISSUE TITLE
Software localization

### ISSUE THREAD

**Issue by Ribero** [leinelissen/jellyfin-audio-player#17]
Hi,

Thanks a lot for the player, I'm already using it everyday !

I would like to contribute and if you are interested I can provide the French localization. I just need to know what's the better way to provide translated strings.

**Comment by leinelissen** [comment]
This sounds like a great idea. I've got most of the software implemented, but it might take a while to fully get it setup. In the meantime, the strings for the English locale are here: https://gist.github.com/leinelissen/47df4b35fa56b6aa9d65aac38d4a8187. If you can create a new JSON with the French language strings, I'll get them in ;)

**Comment by leinelissen** [comment]
Hi @Ribero, I just found out I forgot a couple of strings 😅
Can you either check the Gist I just updated, or help translate it in Transifex: https://www.transifex.com/codified/jellyfin-audio-player/?
Cheers!

**Comment by Ribero** [comment]
Ok for me. I already have a transifex account. You just need to grant me an access (I asked to join)

**Comment by leinelissen** [comment]
Weird I didn't get a notification for that. You should have access to it now!

**Comment by Ribero** [comment]
Done !

**Comment by leinelissen** [comment]
Right, I released the full French locale as build number 5 this morning. If anybody would like to see additional locales added, please create a new issue 🙂

**Comment by Ribero** [comment]
I Just made some updates on the FR version after finding typos.

**Comment by leinelissen** [comment]
Did you put them in Transifex? Can't seem to find them...

**Comment by Ribero** [comment]
Yes I put them as « suugestion » as I was not able to directly submit changes

**Comment by leinelissen** [comment]
Oh right. I managed to find them, the Transifex UI is horrible 😅
I just merged the changes, and they'll come along with the next build. Thanks for your help!

**Comment by Ribero** [comment]
Yeah I know, I do not understand why they made such an awful ergonomics. 
I added comments to let you see were I made suggestions.
