### ISSUE TITLE
10th song in an album has an extra space before the name of the song

### ISSUE THREAD

**Issue by dbolger** [leinelissen/jellyfin-audio-player#172]
For all of the albums I have on my Jellyfin instance, every tenth song on the FinTunes app is showing up with an extra space on the tenth song.

**Comment by SmaMan** [comment]
I think it’s because the extra digit is pushing the titles over by one.

**Comment by SmaMan** [comment]
I think it’s because the extra digit is moving everything over.
![IMG_9136](https://github.com/leinelissen/jellyfin-audio-player/assets/64632222/b0d2a768-ac8c-47c1-aeb1-cc4bc4bca1b0)

**Comment by dbolger** [comment]
Maybe for the sake of the design, the column that contains the current track # should be as wide as it's longest number and the track # could be right-aligned.
