### ISSUE TITLE
App is not loading data

### ISSUE THREAD

**Issue by MindSetFPS** [leinelissen/jellyfin-audio-player#173]
Your app looks promising but unfortunately after connecting to my jellyfin server and loading, the app is completely empty. In settings/Jellyfin library I can see my server and data but it doesn't seem to pull the songs. 

The only uncommon thing about my setup is that every song is in the same directory, no artist subfolder, no albums subfolder.

**Comment by leinelissen** [comment]
Hey there @MindSetFPS, that might be the issue. Fintunes currently only supports playing music from albums or playlists. If you have neither, no music will show up. For more details, you can check out this issue: https://github.com/leinelissen/jellyfin-audio-player/issues/171

**Comment by leinelissen** [comment]
Please do let me know if you manage to work this out.
