### ISSUE TITLE
[Feature Request] Add Disc # Descriptors if avaliable

### ISSUE THREAD

**Issue by McSlamer** [leinelissen/jellyfin-audio-player#179]
It would be nice to have a header or divider with the Disc Number if avaliable. like it is handled in the Jellyfin Web Client or the Jellyfin App. would make it a cleaner look, currently it just groups everything into one whole playlist ignoring the disc metadata.

**Comment by leinelissen** [comment]
Hey @McSlamer, thanks for the input, this would make sense. The data is there as well, so it should be relatively simple implementation. If anyone wants to pick this up, please let me know so I can give som pointers.
