### ISSUE TITLE
Crossfade songs

### ISSUE THREAD

**Issue by Ribero** [leinelissen/jellyfin-audio-player#18]
Would be so nice to have a "Crossfade songs" feature like iTunes (based on duration from 1 to X seconds) or even better an equivalent of the PlexAmp "Sweet fades and Soft transition" feature.

**Comment by leinelissen** [comment]
Hi there! The library the media player is built upon (react-native-track-player) unfortunately doesn't have support for either cross-fading or playing multiple tracks at the same time yet (see https://github.com/react-native-kit/react-native-track-player/issues/670). This means that implementing this feature is currently slightly infeasible 😕

**Comment by leinelissen** [comment]
I will reconsider it though, if it ever makes it to the original library. The pace on it is pretty slow though, so this probably isn't happening in the foreseeable future.
