### ISSUE TITLE
Is this app affected by the libwebp 0day?

### ISSUE THREAD

**Issue by linsui** [leinelissen/jellyfin-audio-player#182]
It uses react-native-skia which doesn't [update libwebp yet](https://github.com/Shopify/react-native-skia/issues/1855). Is it used to display the cover images?

**Comment by leinelissen** [comment]
That's correct, thanks for bringing it up. We're using react-native-skia to render the cover images and blur. The rest is rendered using react-native-fast-image, which I imagine is vulnerable to the CVE as well. I would love to update both dependencies, but I am bound by them making a version available with the fixed version of libwebp. I will check this during this weekend.

**Comment by linsui** [comment]
Looks lIke react-native-fast-image is only affected on iOS. On Android I guess the system libwebp is used.

**Comment by leinelissen** [comment]
I've just updated the react-native-skia version, as well as the downstream libwebp dependency in react-native-fast-image. This covers everything on the iOS side, while libwebp is natively supported on Android, so no action is required from our end.
