### ISSUE TITLE
Why my songs dont appear 

### ISSUE THREAD

**Issue by PitchAbyss** [leinelissen/jellyfin-audio-player#189]
Everything is empty

![Screenshot_20240110_182910_Fintunes.jpg](https://github.com/leinelissen/jellyfin-audio-player/assets/13099434/9a6db0eb-4304-43e3-be79-f00f5fd454ed)

![Screenshot_20240110_182906_Fintunes.jpg](https://github.com/leinelissen/jellyfin-audio-player/assets/13099434/f6599008-7430-4fa4-ba8e-8d3d3c7f398e)

**Comment by kuflierl** [comment]
Your report has very little information that we could use to debug your issue. Some datapoints would be app version, os version, jellyfin version, local vs external server address, jellyfin library type, etc.

My best guess could be that you aren't able to connect to the server for some reason or your library doesn't have the type "music"

**Comment by leinelissen** [comment]
To pitch in here, Fintunes currently only supports the `MusicAlbum` type. This means that if your music is organised some other way, for instance only through tracks, we currently support listening to those.
