### ISSUE TITLE
Pick colors, red in black not ideal for color blindness 

### ISSUE THREAD

**Issue by Japhys** [leinelissen/jellyfin-audio-player#194]
Just found this app and giving it a try. Like it very much.

I do have some problems with the red font. For the color blind this is not ideal, at least not for me :) Maybe give some options?

**Comment by leinelissen** [comment]
This should now be fixed with v2.3.0 🚀. I've taken some time to pick colours that could work out better. Would you care to review them once I manage to get it out on TestFlight?
