### ISSUE TITLE
Dark mode bug

### ISSUE THREAD

**Issue by PauFCB** [leinelissen/jellyfin-audio-player#198]
Hi, when light mode its enabled in system preferences and dark mode on fintunea this happens: (only work if both are in dark mode.
![IMG_2765](https://github.com/leinelissen/jellyfin-audio-player/assets/55207285/ec002bbe-ddf8-4d37-9c9a-89cfd0305387)

**Comment by leinelissen** [comment]
Hey @PauFCB, thanks for noticing! I can confirm this is a problem, and I'd love to get a fix in for this.
