### ISSUE TITLE
Rollout 2.3.0 release to ios App Store

### ISSUE THREAD

**Issue by vijayvcm** [leinelissen/jellyfin-audio-player#200]
Hello,

I have seen this new Fintunes 2.3.0 release has been out but I couldn’t see this reflected on the iOS App Store. 

Do we have any timeline on when this will be published to App Store?

**Comment by leinelissen** [comment]
Heya, thanks for the message! 2.3.0 has been out on TestFlight, where I was just seeing if any major issues popped up. I've been really busy the past week, so I didn't get around to pushing it to release just yet. I'll do that right now, and it will probably hit the App Store somewhere this weekend or right after.

**Comment by vijayvcm** [comment]
Looking forward to the new release!

Thanks, @leinelissen

**Comment by msoucy** [comment]
It looks like it's been uploaded to the app store. Is there any chance that f-droid can get the update as well?

**Comment by leinelissen** [comment]
It is! As for F-Droid, something broke the build for it. I have attempted to dive in there to solve the problem, but it requires a bit more work to fix the problem. Hope to make some time for this.

**Comment by leinelissen** [comment]
The build updates just got merged into F-Droid. As soon as the build server makes a new pass, the update should appear on F-Droid. This may take a couple days at most.
