### ISSUE TITLE
Local playback only?

### ISSUE THREAD

**Issue by inconnel** [leinelissen/jellyfin-audio-player#207]
It is not possible to play music using google cast/DLNA in Fintunes (android), local playback only on my phone. In Jellyfin app everything works as expected. Any idea?

**Comment by leinelissen** [comment]
Hey there, thanks for reporting this. I'm not too familiar with Android devices myself, but you should be able to cast audio using your built-in Android media player. Fintunes doesn't have any built-in Google Cast capability right now, because the underlying media libraries don't support it.

**Comment by leinelissen** [comment]
You may track progress for that in #37, but until then there's nothing I can do.
