### ISSUE TITLE
[Feature Request] Book/Audiobook support

### ISSUE THREAD

**Issue by HBIDamian** [leinelissen/jellyfin-audio-player#219]
Currently the latest fdroid update doesn't support audiobooks that are under the "Books" library. 
Supporting it would be nice

**Comment by leinelissen** [comment]
Hey, thanks for the suggestion! I would love to see this happen, but it's not a priority at this moment. I will be closing this issue as it is a duplicate of #79, where any support for audiobooks will be tracked.
