### ISSUE TITLE
Improving album cover display

### ISSUE THREAD

**Issue by vmazmaz** [leinelissen/jellyfin-audio-player#226]
On iOS, when clicking on an album from the album list, it takes slightly more time to load the album cover than on Android for some reason.

In addition, sometimes there is a cogwheel spinning at the top, sometimes not. I think it looks cleaner without. Perhaps a fade in animation like in Finamp would smooth the UX ?

Finally, it would be a nice touch to have the default album cover to match the selected app theme. The default cover is white even when the dark theme is enabled.

This is just some nitpicking, Fintunes is already by far the cleanest music client for JF :)

**Comment by leinelissen** [comment]
Hmm the different loading times is a weird one to me, as the logic is all the same 😅. The spinning wheel is sometimes triggered automatically after a couple days to refresh the latest albums and hold hide again when it completes. And as far as the album cover goes, that's a bug that I will look into ;).
