### ISSUE TITLE
The album section is ordered by the artist and not the album name.

### ISSUE THREAD

**Issue by Else00** [leinelissen/jellyfin-audio-player#239]
Can you please add possibility to order by album name and not artist?

**Comment by leinelissen** [comment]
Hey there @Else00, thanks for the feedback! This is a much requested feature. I would love to get this in, but I'm a bit short on time. If you are interested in making a contribution, I'd love to give you some pointers.

**Comment by leinelissen** [comment]
There is another issue in which I will be tracking support for this feature. Duplicate of #216.

**Comment by leinelissen** [comment]
There is another issue in which I will be tracking support for this feature. Duplicate of #216.
