### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by Wierdio** [leinelissen/jellyfin-audio-player#3]
Is there Dark Mode compatibility and if I build it does it actually work?

**Comment by leinelissen** [comment]
Hi there!

Dark mode support is not here yet, but should be relatively easy to implement. I use the iOS version daily, which is minimal but very functional. Android should work as well, but I haven't gotten around to testing it yet. If you are willing to help out with any of these issues I would be glad to accept a pull request.

**Comment by leinelissen** [comment]
Hi @Wierdio, FYI: I've just added dark mode support for both Android and iOS.

**Comment by Wierdio** [comment]
Thank you!

**Comment by Wierdio** [comment]
Has dark mode support been added to the releases page IPA?

**Comment by leinelissen** [comment]
> Has dark mode support been added to the releases page IPA?

It has now 😁
