### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by thornbill** [leinelissen/jellyfin-audio-player#36]
We are big fans of the work you are doing here and want to support third party clients as much as possible. We do request that third party apps avoid using the name Jellyfin in the name of the app. This is just to try to make it clear for users that the app is not an official project so any issues, feedback, etc. get directed to the right place. Thanks!

**Comment by leinelissen** [comment]
@thornbill again, this is a fair request and I probably should have seen this coming 😅. If it's okay with you, I will need to take some time to dream up a name hits all the right SEO spots and integrate it in the app itself.

**Comment by thornbill** [comment]
👍 I would just say preferably before you release on the App Store. I just wanted to bring it up now so hopefully it won’t be too much of a headache.

**Comment by dkanada** [comment]
@leinelissen good luck with the SEO efforts, I'm pretty sure every possible variation of `JellyX` or `jf-x` is taken by now :laughing:

**Comment by leinelissen** [comment]
> 👍 I would just say preferably before you release on the App Store. I just wanted to bring it up now so hopefully it won’t be too much of a headache.

That works for me. The headache is mostly in losing that sweet sweet SEO haha. I'll get over it :)

**Comment by leinelissen** [comment]
Closing this as v2.0.0 changed the app name to Fintunes. It's also [on the App Store](https://apps.apple.com/nl/app/fintunes/id1527732194?l=en) now.
