### ISSUE TITLE
is it possible to release an IPA?

### ISSUE THREAD

**Issue by 27md** [leinelissen/jellyfin-audio-player#4]
would it be possible to release an IPA file for users to sideload with altstore until the app is on AppStore?

**Comment by leinelissen** [comment]
I've created and released an IPA here: https://github.com/leinelissen/jellyfin-audio-player/releases/tag/v0.0.1-alpha0. I would love to generate these automatically using GitHub actions, but I unfortunately do not possess an Apple Developer License, so I am currently unable to do so. 

Let me know if this works out for you.

**Comment by Darkwolf1515** [comment]
That Ipa does not seem to be the latest, as theres no dark mode.

Also am I meant to be able to change the bitrate? because I cannot.

**Comment by leinelissen** [comment]
There has been a new release since, which you can find on the releases page: https://github.com/leinelissen/jellyfin-audio-player/releases. Let me know if v0.0.1-alpa1 is working out for you. Also, the bitrate selector is a placeholder for now, while I work out how Jellyfin calculates bitrates.

**Comment by leinelissen** [comment]
> There has been a new release since, which you can find on the releases page: https://github.com/leinelissen/jellyfin-audio-player/releases. Let me know if v0.0.1-alpa1 is working out for you. Also, the bitrate selector is a placeholder for now, while I work out how Jellyfin calculates bitrates.

Disregard the first thing. I checked out the IPA, and there was an issue in the build pipeline which caused the IPA to be loaded with an outdated bundle. This is now fixed, and I have verified that the latest release includes the correct bundle.

**Comment by Darkwolf1515** [comment]
> > There has been a new release since, which you can find on the releases page: https://github.com/leinelissen/jellyfin-audio-player/releases. Let me know if v0.0.1-alpa1 is working out for you. Also, the bitrate selector is a placeholder for now, while I work out how Jellyfin calculates bitrates.
> 
> Disregard the first thing. I checked out the IPA, and there was an issue in the build pipeline which caused the IPA to be loaded with an outdated bundle. This is now fixed, and I have verified that the latest release includes the correct bundle.

Thank you! I’ll try it out.

**Comment by drazil100** [comment]
Can you add some sort of instructions on how to load builds? I would like to try these but I don't know how to add them.

If it require iTunes unfortunately I will have to wait for the test flight build cause I run linux and apple doesn't care about linux to release iTunes for it.

**Comment by Darkwolf1515** [comment]
Nope, Itunes has nothing to do with it, apple would never let people easily add ipa's.

I used alt server to sideload them, but thats windows and mac only, https://altstore.io/ 

Apps will only work for 7 days, then you must connect them back to the computer and renew them.

**Comment by drazil100** [comment]
Much as I want to test I'm gonna have to wait until TestFlight. Let us know on this issue when there is a build to try and I'll hop right to testing it :)

**Comment by leinelissen** [comment]
Happy to report that TestFlight is now available! See https://testflight.apple.com/join/cf2AMDpx.
Again, any feedback is duly appreciated. Please do create a new ticket for it ;)
