### ISSUE TITLE
App extremely unresponsive on my device (Android)

### ISSUE THREAD

**Issue by Vodes** [leinelissen/jellyfin-audio-player#40]
Android Version: 10 (LineageOS)
Device: Samsung Galaxy S9

[A video of whats happening](https://files.catbox.moe/lbq4e1.mp4)
You can see the tap indicators

Playback also doesnt seem to be working. My music on jellyfin is in the opus codec

**Comment by leinelissen** [comment]
Hmm, right. I'll try and run on an Android emulator to see if I can replicate the issue. Can you check if this is an issue with the particular device, or a general Android issue?

**Comment by leinelissen** [comment]
Thanks for reporting by they way!

**Comment by Vodes** [comment]
Currently at work. Will be at home in like 3 hours. Can try another device then ^^

**Comment by Vodes** [comment]
Sorry that im a little late. Just tried it on my Tablet (Lenovo Tab p11, also android 10, but not a custom rom) and it has the same issue.

**Comment by leinelissen** [comment]
Alright, I was able to reproduce the error. A component that was responsible for fetching the current track was rerendering in an infinite loop. This has now been fixed, and the `v0.1.4` release is currently brewing with a fix for this issue. I'd love to hear whether this resolves your problems.

**Comment by Vodes** [comment]
Its now as responsive as it should be yeah. The playback still doesnt seem to work... I am willing to provide a temporary account to my server if you can message me somewhere else. [This is the log](https://bin.vodes.pw/?70fe062e9227294e#9aqarq44vrPFzrpwEMQQg6uS8MGumr2sEFxdhV73BF8w)
