### ISSUE TITLE
Ios app capable of downloading out, might be useful.

### ISSUE THREAD

**Issue by Darkwolf1515** [leinelissen/jellyfin-audio-player#41]
(I would have used discussions but they’re not enabled)

https://github.com/UnicornsOnLSD/finamp

it’s capable of downloads, so maybe it’s a good idea to look at its implementation:)

**Comment by leinelissen** [comment]
Right, good catch! Unfortunately the app is written in Flutter, so it's quite hard to copy it 1-on-1, but I'll take a look and try to find some inspiration :)
