### ISSUE TITLE
HTTP no longer supported

### ISSUE THREAD

**Issue by thornbill** [leinelissen/jellyfin-audio-player#42]
It seems like https is required in the latest update.

![363ED77A-3B7A-4649-B927-ADBE0A3D5A0E](https://user-images.githubusercontent.com/3450688/116001115-f654f980-a5c0-11eb-8655-f38068cfaf50.png)

**Comment by leinelissen** [comment]
Curious that this was working in the previous version, but it might be a weird dependency issue. Anyways, thanks for catching this so quickly. I am currently running the pipeline to deploy a new version where this should be fixed. You'll find a new update soon'ish™️. Please do let me know if this fixes stuff for you

**Comment by thornbill** [comment]
Seems to work now! Thanks!
