### ISSUE TITLE
Add A Tell Client The App Is Offline Feature 

### ISSUE THREAD

**Issue by TECHNETWORKINGSOLUTIONS** [leinelissen/jellyfin-audio-player#48]
Hey I Was Testing The App, Great App By The Way, But I came across one minor thing. I was wondering if there is anyway you could add a feature that will tell you if you are offline/not connected to the internet or server.
It just really to help my clients not get confused as to why the app looks like it’s loading the song when it’s not connected in the first place.

Cheers-TNS

**Comment by leinelissen** [comment]
This seems like a worthwhile addition. I'll see if there is a straightforward way to implement this.

**Comment by TECHNETWORKINGSOLUTIONS** [comment]
Alright Sounds Good

**Comment by leinelissen** [comment]
This was released as part of v0.2.1 and v0.2.2 and should now be available on TestFlight and the [releases page](https://github.com/leinelissen/jellyfin-audio-player/releases).
