### ISSUE TITLE
Cant login on android.

### ISSUE THREAD

**Issue by EGDPG** [leinelissen/jellyfin-audio-player#59]
Browser pop sits on users that I should be allowed to tap, however its just froze in place. Any ideas?
Thanks.

**Comment by leinelissen** [comment]
Hi Gonjat, I've just cut a new release with many upgraded dependencies: https://github.com/leinelissen/jellyfin-audio-player/releases/tag/v0.2.0. I tried to see if I could replicate the problem on the emulator, but everything seems fine. Could you check it out and let me know if it works?

**Comment by ne0phyte** [comment]
I'm having the same issue. Tested just now with the 0.2.3 apk and was not able to tap anything on the jellyfin login page.

Android Version: Android 12 (January 22 Update)
Android Device: Google Pixel 6
Jellyfin Server: 10.7.6

I don't develop for Android so I have no idea if there is anything useful but here is a logcat log of opening the app, tapping "Set Jellyfin Server", pasting my server URL and then the login page coming up. 

[logcat.log](https://github.com/leinelissen/jellyfin-audio-player/files/7877342/logcat.log)

**Comment by leinelissen** [comment]
Yeah thanks for the update there. I have absolutely no clue what's going on. I'll see if I can get my hands on an Android device and debug what's going on here.

**Comment by UnironicBadger** [comment]
I just installed v0.2.3 apk and I also cannot log in. I can type the server, connect and see users but on the users page I cannot tap on any user nor can I tap on manual login. 

Android Version: Android 12 (March 2022 update)
Android Device: Google Pixel 4a 5g
Jellyfin Server: 10.7.7 (docker container)

I'd be happy to help in any way I can but I don't know literally anything about coding/development. 
Thank you all for all that you do on this project

**Comment by leinelissen** [comment]
Hey there! I finally managed to sort out an Android phone to debug the issue. Turns out there were some competing nested pressables that were competing with each other. Please try out [the new release](https://github.com/leinelissen/jellyfin-audio-player/releases/tag/v1.2.4) and let me know if this works for you.

**Comment by leinelissen** [comment]
Hey @bannert1337, this is a closed issue for a separate bug. Could you maybe create a new issue and mention which app version you're using and which Jellyfin server version?
