### ISSUE TITLE
Any way to shuffle and loop all music on the iOS client?

### ISSUE THREAD

**Issue by hwittenborn** [leinelissen/jellyfin-audio-player#6]
Title explains itself. If it's not a feature, I kindly ask that as a request.

**Comment by leinelissen** [comment]
Not, yet but it's duly noted and considered. Should be doable to implement.

**Comment by hwittenborn** [comment]
Good good

**Comment by leinelissen** [comment]
Repeat mode has been implemented, but shuffle functionality is blocked upstream by react-native-track-player: https://github.com/react-native-kit/react-native-track-player/pull/688. I hope they can figure something out, before I need to get my hands dirty on iOS native code...

**Comment by leinelissen** [comment]
This should be out with the new Testflight update anytime now. Shuffle might be slightly more feasible now I've had to implement tracking for queue changes anyway. I'll keep you posted.

**Comment by hwittenborn** [comment]
Didn't even know there was a TestFlight for Jellyfin. I'll definitely join it(assuming slots are open)!

**Comment by hwittenborn** [comment]
oof looks like it's closed

**Comment by leinelissen** [comment]
> Didn't even know there was a TestFlight for Jellyfin. I'll definitely join it(assuming slots are open)!
> Edit: Appears to be closed -- any chance it can be reopened?

It should be open! What are you running into?

**Comment by hwittenborn** [comment]
It’s telling me it’s full, might be an old link though.
Would you mind sharing the link to the beta?

**Comment by leinelissen** [comment]
I've double-checked, but it seems to work from my end 🤨. The link is https://testflight.apple.com/join/cf2AMDpx. If it's not working out, drop me an e-mail at lei@codified.nl and I'll add your email manually.

**Comment by hwittenborn** [comment]
That link worked, thank you!
