### ISSUE TITLE
Change the track progress bar

### ISSUE THREAD

**Issue by httpjamesm** [leinelissen/jellyfin-audio-player#61]
The current track progress bar is inconsistent with Apple design language (which I assume is what you were going for). 

It looks like a volume slider, when in reality it's a track slider. 

![image](https://user-images.githubusercontent.com/51917118/138793860-9e9f30fd-52f8-4c45-b49b-bbf2cca3a552.jpeg)

I would suggest instead using the Apple Music style track slider and adding a volume slider.

**Comment by leinelissen** [comment]
This should now be a lot closer to what we're looking for. Check out the latest release ;)
