### ISSUE TITLE
Can only play a single song from anywhere or the whole album from the beginning. 

### ISSUE THREAD

**Issue by drazil100** [leinelissen/jellyfin-audio-player#7]
There is no obvious way to start an album from the middle and have it continue to play the rest of the album from there. 

I have quite a few large albums in my library including several pokemon game soundtracks which are pretty large (heart gold soul silver's is 268 tracks long). Not being able to start an album from the beginning is kinda an annoying limitation.

**Comment by drazil100** [comment]
The most obvious solution to this would be a way to switch modes (like play one, play all, loop 1, loop all, shuffle)

**Comment by leinelissen** [comment]
Thanks for your feedback! I think the Apple music way of doing this is; when selecting an album song, add the album to the queue and start playing from the selected song onwards. I am looking at adding loop and shuffle functionality to the player window specifically. Would this work for you?

**Comment by drazil100** [comment]
Pretty sure jellyfin also uses a queue. I definitely prefer a queue to no queue.

**Comment by leinelissen** [comment]
This should be fixed with the new build on TestFlight. Do let me know if this works better for you, or if there are other improvements I can make ;)

**Comment by drazil100** [comment]
Ill check it out and let you know when we get stable power back. Got hit by the hurricane and we will be having rolling power for a few days and I don't want to have my server online during this time so no jellyfin :(

**Comment by leinelissen** [comment]
> Ill check it out and let you know when we get stable power back. Got hit by the hurricane and we will be having rolling power for a few days and I don't want to have my server online during this time so no jellyfin :(

Oh wow, hope you're doing okay!
