### ISSUE TITLE
App permissions

### ISSUE THREAD

**Issue by EdenVisionCorp** [leinelissen/jellyfin-audio-player#71]
Hi, any chance you can disclose the app permissions? I would love to support the beta testing on both ios and android and I would feel more comfortable knowing, thanks

**Comment by leinelissen** [comment]
Hi there! The app permissions can be found in the following files:
* iOS: https://github.com/leinelissen/jellyfin-audio-player/blob/master/ios/JellyfinAudioPlayer/Info.plist
* Android: https://github.com/leinelissen/jellyfin-audio-player/blob/master/android/app/src/main/AndroidManifest.xml

As you can see we're working with nothing special. Mainly comes down to internet access for your Jellyfin instance, as well as background modes for audio and downloading files. There's also an in-app request for sharing crash and debug data to a self-managed server, but you can decline if you want.

Happy to see you try things out!

**Comment by EdenVisionCorp** [comment]
Hi Lei, awesome thanks! is there any email, or other way to give you feedback other than opening issues?

**Comment by leinelissen** [comment]
Opening issues is of course the preferred way, but if you're looking for a private channel, you can find my email on my Github profile ;).
