### ISSUE TITLE
Fdroid release?

### ISSUE THREAD

**Issue by Seb3thehacker** [leinelissen/jellyfin-audio-player#78]
Have you considered releasing this amazing app on F-Droid?
Thanks!

**Comment by leinelissen** [comment]
Hey @Seb3thehacker! Thanks for the comments. I am currently working on a bit of a design overhaul and afterwards I will be releasing the application on preferably all the app stores. It's a good idea to include F-Droid as well. Should be somewhere in the coming months.

**Comment by Seb3thehacker** [comment]
Love it! Take your time! ❤️

**Comment by kuflierl** [comment]
What is the current status?

**Comment by leinelissen** [comment]
Currently working on getting 2.0 out to the App Store. Google Play will be afterwards, then F-droid. Since the build will be built by F-droid I will need to overhaul the build system a teeny bit. Making good progress, but it'll still take some time.

**Comment by RealStickman** [comment]
If you don't (yet) want to deal with F-droid inclusion, there are third-party repos where inclusion is easier than the main repo.  
For example IzzyDroid uses your published APK, see [details](https://apt.izzysoft.de/fdroid/index/info) and [requirements for app inclusion](https://gitlab.com/IzzyOnDroid/repo/#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo)  
Thank you for your work, I still have some more testing to do, but your app already looks very polished for my use case.

**Comment by leinelissen** [comment]
I'm well underway in getting Fintunes on F-Droid and I would prefer to go for F-Droid directly. You can track the repository where I'm working on inclusion here: https://gitlab.com/leinelissen/fdroiddata. The process has been quite finicky though because of the large amount of native dependencies. If anyone has any experience with getting stuff onto F-Droid, any help is appreciated.

**Comment by leinelissen** [comment]
Fintunes is now available on F-Droid! Find it here: https://f-droid.org/en/packages/nl.moeilijkedingen.jellyfinaudioplayer/
