### ISSUE TITLE
The App crashes when trying to open it

### ISSUE THREAD

**Issue by SandwichFox** [leinelissen/jellyfin-audio-player#85]
Hey! The App Android version crashes when i try to open it.
Im using the latest release (v1.2.5) and Android 12 (OneUI)
I also tried it on multiple devices.
You can see more in the video attached to this Issue
[Video of crash ](https://www.youtube.com/watch?v=sSvRZsmx0HE)

**Comment by leinelissen** [comment]
Hey @SandwichFox! Thanks for the report. I am aware of an issue with the latest Android build because of a dependency update. I haven't been able to narrow it down yet, but I am looking into it. Until this issue is fixed, I recommend using v1.2.4. I'll close this issue once the crash is resolved

**Comment by leinelissen** [comment]
Hey @SandwichFox, I've released a beta version which should address this issue. Could you maybe check if it's working out for you? You can find it here: https://github.com/leinelissen/jellyfin-audio-player/releases/tag/v1.2.6-beta.1

**Comment by leinelissen** [comment]
Perfect, I'll try and release a stable version soon.
