### ISSUE TITLE
[Bug/Isssue] Time left of songs is always wrong

### ISSUE THREAD

**Issue by florinsdistortedvision** [leinelissen/jellyfin-audio-player#90]
Just as the name implies, regardless of what song I play it always shows values between -30 seconds and -45-50seconds. 

iOS (TestFlight) latest version > iOS 15 

Edit : photos attached

![image](https://user-images.githubusercontent.com/97384306/183121656-1d05473d-881c-42f6-be85-3b04c037a9cd.png)

![image](https://user-images.githubusercontent.com/97384306/183121666-10d76572-669f-4618-ab99-241bbec07eb4.png)

![image](https://user-images.githubusercontent.com/97384306/183121680-b25065b5-02a9-4fc1-9a07-2a3a4bdab588.png)

![image](https://user-images.githubusercontent.com/97384306/183121700-c2f420b6-e544-42ae-9cbc-3d34c4be698a.png)

**Comment by leinelissen** [comment]
Hey @florinsdistortedvision! Thanks for submitting this bug. This is a curious one! Since we take the the duration time directly from a library, my first guess would be that it's got something to do with the files that are being served by your Jellyfin instance. What kind of audio formats are you using? And would you have a chance to test this behaviour against other Jellyfin servers?

**Comment by florinsdistortedvision** [comment]
> Hey @florinsdistortedvision! Thanks for submitting this bug. This is a curious one! Since we take the the duration time directly from a library, my first guess would be that it's got something to do with the files that are being served by your Jellyfin instance. What kind of audio formats are you using? And would you have a chance to test this behaviour against other Jellyfin servers?

Hello, all my files are flac 16 bit 44.1khz. I did try with another player (Finamp) and they do show correctly the time left and everything.

Files are played from a cloud computer + cloud storage (via rclone on Ubuntu).

**Comment by leinelissen** [comment]
I'll send you credentials for my Jellyfin Demo server over Twitter DM. Could you use those and check if the issue persists? Cheers!

**Comment by florinsdistortedvision** [comment]
> I'll send you credentials for my Jellyfin Demo server over Twitter DM. Could you use those and check if the issue persists? Cheers!

Sure, tho do keep in mind I can only test on my iOS device (don't have other phones sorry).

**Comment by leinelissen** [comment]
This issue is resolved with the new FLAC playback capability in v1.2.7. While it remains an issue when audio files need to be transcoded, a fix is incoming for a later version as well.

**Comment by florinsdistortedvision** [comment]
Thank you, it's great that you managed to figure it out!
