### ISSUE TITLE
[Bug] IOS app can't play back music downloaded before update

### ISSUE THREAD

**Issue by kuflierl** [leinelissen/jellyfin-audio-player#93]
The iOS app fails to play back  content that was downloaded on the 1.2.5 release on the new 1.2.6 release after the update. The content shows up but the time remaining stats at -0:00 and a loading symbol is present in the minimized player view which was not present before.

I am not in fact sure if this issue will persist after a deletion and redownload of the content as I don't have the necessary datacap allowance to download anything.

**Update:**

I have indeed verified that only content downloaded before the update is affected. It seems that re-downloading the media resolves the issue.

**Comment by leinelissen** [comment]
Hey @kuflierl, thanks for submitting this! There was nothing in the v1.2.6 update that should affect downloads in any way. I'll try and run some tests to see if downloads get persisted as they should. In the meantime, v1.2.7 should be released pretty soon. Can you please check if the same issue arises when updating this time?

**Comment by PauFCB** [comment]
I have a similiar issue. In my case with a .m4a and a .mp3 previously added to a playlist and downloaded (all with 1.2.5 version). Now I can play those songs via the album view but not thru the playlist view and I can’t re-download, nothing happens when I click the download button. Also I try to re scan my library and reset caché but still not work.

**Comment by kuflierl** [comment]
> Hey @kuflierl, thanks for submitting this! There was nothing in the v1.2.6 update that should affect downloads in any way. I'll try and run some tests to see if downloads get persisted as they should. In the meantime, v1.2.7 should be released pretty soon. Can you please check if the same issue arises when updating this time?

Sorry for reporting late. I hadn't been in the mood to listen music from my phone for a while now. It seems that 1.2.7 also nuked the database. I also have seen a new issue pop up. I had a partial download before I updated. That download seems to be stuck with no clear way of fixing it (inactive delete button, download button does nothing and delete in failed downloads also does nothing). After trying to redownload a know good before update album it seems like it is also stuck (probably queue issues). After clearing the cache it seems like all failed downloads but 5 have been removed from the queue (all downloads before update).

Any tips on removing the downloads from the queue?

**Comment by leinelissen** [comment]
Hey @kuflierl. Sorry for only getting back to you now. Unfortunately there is no way to reset the full database / downloads currently. This is something I need to build out for the next version. I'm also working on the file download logic to address the issues you mentioned.

**Comment by kuflierl** [comment]
Alright, it seems like version 2.0 removed the broken downloads. Should I close this issue? @leinelissen
