### ISSUE TITLE
Android - Play album, shuffle album, Play playlist buttons not working

### ISSUE THREAD

**Issue by myogui** [leinelissen/jellyfin-audio-player#99]
On version 1.27, I can navigate to an album or playlist, but the play button won't react to touch. I am able to start playback by touching the second or third song in the list and then selecting the first from the queue.

I'm on a Realme device, so Realme UI 3.

**Comment by slapelachie** [comment]
I can confirm that I am having the same issue. However, I have noticed that the first item can be selected on random albums, not sure what makes it work for these albums. Currently running LineageOS 18.1 so the problem might be universal.

**Comment by mcgrew** [comment]
Same issue here on a Pixel 4a with Android 13. In addition the "Download Playlist" button lights up when clicked but doesn't seem to do anything.

**Comment by pedrotrschneider** [comment]
I am also having the same issue on a Motorola Edge 20, android 12.

**Comment by leinelissen** [comment]
Hey all, thanks for the input. I'm investigating this.

**Comment by JaxzKyd** [comment]
> Hey all, thanks for the input. I'm investigating this.

It's closing in on 2 months, how's the investigating going?

**Comment by leinelissen** [comment]
Hi all, I'm really sorry it's taking so long, but I've been incredibly busy over the past couple months so I haven't had much time to work on this app. Good news though! I've located the problem and created a fix. I'm going to test everything extensively tomorrow and then release it for you guys.

**Comment by leinelissen** [comment]
A fix for this is released in v2.0.0. Let me know if this solves the issue.

**Comment by myogui** [comment]
> A fix for this is released in v2.0.0. Let me know if this solves the issue.

Yep works flawlessly, thanks for the new version and fix mate!
